### ISSUE TITLE
Can't find module "pync"?

### ISSUE THREAD

**Issue by cdl** [sindresorhus/weechat-notification-center#11]
Hey there,

I've installed the plugin (and have `python 2.7.10` installed via `pyenv`) as well as done a `pip install pync`, but on load of the plugin, this happens:

```
python: stdout/stderr: Traceback (most recent call last):
python: stdout/stderr:   File "/Users/colby/.weechat/python/autoload/notification_center.py", line 6, in <module>
python: stdout/stderr:     from pync import Notifier
python: stdout/stderr: ImportError: No module named pync
python: unable to parse file "/Users/colby/.weechat/python/autoload/notification_center.py"
```

I'm assuming it's because it can't find the `pync` package I've installed? What can I do to get it to recognize my `pyenv` Python install? It definitely is installed, because when I try it out via the Python REPL, I get this (with the notification appearing properly):

![image](https://cloud.githubusercontent.com/assets/753413/12870709/71fb430a-cd0e-11e5-8e6d-63e8575c62ba.png)

Hope you can help me out! Let me know if you need anything else from me.

**Comment by sindresorhus** [comment]
I don't really know. I'm not using Python much these days. And your question is not really specifically related to this plugin either, but rather imports with pyenv. You could try asking on Stack Overflow.

Maybe some earlier contributors could help: @Quentin-M @williamleuschner @ikanusim

**Comment by Quentin-M** [comment]
Hi.

Weird. Make sure you are in a virtualenv somehow.

**Comment by thiagopnts** [comment]
I had a similar issue awhile ago. In the end the client was using a different python version then the one I was installing pync. You might try checking in which python versions(including the ones you have on the system) you have pync installed, e.g. python2, python2.6 and python2.7

**Comment by leoj3n** [comment]
I have found this same issue with `pyenv`+`weechat` installed via Homebrew.

WeeChat is built using `cmake`: https://github.com/weechat/weechat/blob/master/Makefile.am#L58

I don't really know much about `cmake`, but my guess is it "finds" the `system` python instead of `pyenv`.

Maybe we need to tell WeeChat's `cmake` to use `pyenv` [like this](http://stackoverflow.com/questions/15291500/i-have-2-versions-of-python-installed-but-cmake-is-using-older-version-how-do)?

Can someone with more knowledge on the subject confirm whether or not the problem is indeed in how WeeChat builds itself, or maybe is it a problem with how Homebrew builds WeeChat? Certainly it's not a problem with `weechat-notification-center` but not sure where to go next.

**Comment by SteveJobzniak** [comment]
@leoj3n Thanks, you put me on the right track!

The trick is: "python" from homebrew must be installed BEFORE you install weechat via homebrew. Otherwise weechat links to macOS "python2" install, which lacks the ability to load all libraries.

I don't use pyenv. Instead, I always use "python2/python3/pip2/pip3" prefixes to specify which version I want.

Here's how I fixed my weechat which had been installed before I had homebrew's python2:

```
brew uninstall weechat
brew install python3
brew install python
brew unlink python && brew link python # make sure python links to python2
pip2 install --upgrade pip setuptools # upgrade to latest pip2
pip3 install --upgrade pip setuptools # upgrade to latest pip3
pip2 install pync
brew install weechat --with-perl --with-python --with-ruby --with-lua
```

After that, my weechat worked and was able to use pync!

So all that remained was to do was this in weechat:

```
/script install notification_center.py
/script autoload notification_center.py
```

Success!

**Comment by rodrigomaia17** [comment]
REALLY THANKS @leoj3n and @SteveJobzniak

**Comment by SteveJobzniak** [comment]
@rodrigomaia17 I am just happy to see that people keep finding this solution. It took me a few hours to solve so if I can save that time for others then I am happy.

@sindresorhus Turns out this situation is a very common problem for people using Homebrew on a Mac, so perhaps it should be in the official plugin description for those who cannot find my comment. ;)
