### ISSUE TITLE
Shows notifications for messages I send

### ISSUE THREAD

**Issue by Noah-Huppert** [sindresorhus/weechat-notification-center#22]
notification_center.py will send notifications for messages that I send. I noticed this behavior only  when using the wee-slack plugin. So I believe it has something to do with how this plugin displays messages.

**Comment by tubbo** [comment]
@Noah-Huppert I ran into this issue as well. I have a funny feeling that wee-slack doesn't export the `localvar_nick` variable, because that's what's being checked against in [the guard clause to ignore your own messages](https://github.com/sindresorhus/weechat-notification-center/blob/master/notification_center.py#L36-L39).

**Comment by chunkhang** [comment]
I faced this issue when using `wee-slack`. I just added an additional check to ignore notifications if the message is coming from the current buffer you're viewing.
```
if prefix == ('@%s' % own_nick) or prefix in tags or buffer == weechat.current_buffer():
	return weechat.WEECHAT_RC_OK
```

**Comment by sindresorhus** [comment]
@chunkhang Interested in doing a pull request?

**Comment by chunkhang** [comment]
> @chunkhang Interested in doing a pull request?

Sure thing
